
### accounts local
http://localhost:9061/accounts/search?customerId=2f1b862e-57df-417c-a98a-67ebc8ad3aae

### account local
http://localhost:9061/accounts/82f1b952-f9ac-49a3-9ddb-998a7791df32

### transactions local
http://localhost:9061/accounts/82f1b952-f9ac-49a3-9ddb-998a7791df32/transactions

### accounts remote
https://dev-ms-accounts-sg.azurewebsites.net/accounts/search?customerId=2f1b862e-57df-417c-a98a-67ebc8ad3aae